apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-on-call-bot.fullname" . }}
  labels:
    {{- include "matrix-on-call-bot.labels" . | nindent 4 }}
data:
  config.yaml: |-
    database:
      driver: {{ .Values.database.driver | quote }}
      host: {{ .Values.database.host | quote }}
      port: {{ .Values.database.port }}
      db_name: {{ .Values.database.dbName | quote }}
      username: {{ .Values.database.username | quote }}
      password: {{ .Values.database.password | quote }}
      timeout: {{ .Values.database.timeout | quote }}
      read_timeout: {{ .Values.database.readTimeout | quote }}
      write_timeout: {{ .Values.database.writeTimeout | quote }}
      connection_lifetime: {{ .Values.database.connectionLifetime | quote }}
      max_open_connections: {{ .Values.database.maxIdleConnections }}
      max_idle_connections: {{ .Values.database.maxOpenConnections }}

    matrix:
      display-name: {{ .Values.matrix.displayName | quote }}
      token: {{ .Values.matrix.token | quote }}
      url: {{ .Values.matrix.url | quote }}
      userID: {{ .Values.matrix.userID | quote }}
