apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-on-call-bot.fullname" . }}
  labels:
    {{- include "matrix-on-call-bot.labels" . | nindent 4 }}
spec:
  ports: []
  clusterIP: None
  selector:
    {{- include "matrix-on-call-bot.selectorLabels" . | nindent 4 }}
