name: golangci-lint

on:
  push:
    branches: ['*']

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        name: golangci-lint
        with:
          version: v1.46.2
